#!/bin/bash
#Mr.s0s.X..!?/.>#

#variables
b='\033[1m'
u='\033[4m'
bl='\E[30m'
r='\E[31m'
g='\E[32m'
bu='\E[34m'
m='\E[35m'
c='\E[36m'
w='\E[37m'
endc='\E[0m'
enda='\033[0m'
blue='\e[1;34m'
cyan='\e[1;36m'
red='\e[1;31m'
spath="$( cd "$( dirname $0 )" && pwd )"

cowsay -f dragon "KUY" | lolcat
figlet -f slant "KONTOOLSV2" | lolcat

echo "•••••••••••••••••••••••••••••••••••••••••" | lolcat
echo "Tools    : KONTOOLS V2" | lolcat
echo "Creator  : ./Mr.s0s" | lolcat
echo "Email    : xhubiloxs357@gmail.com" | lolcat
echo "whatsapp : 08878819132" | lolcat
echo "Team     : G4L4XY CYB3R T34M" | lolcat
echo "••••••••••••••••• GCT •••••••••••••••••••" | lolcat
echo ""

###################################################
# CTRL C
###################################################
trap ctrl_c INT
ctrl_c() {
clear
echo "[#]> (Ctrl + C ) Detected, Trying To Exit ... " | lolcat
sleep 1
echo ""
echo "[#]> Terima kasih sudah make tools saya ... " | lolcat
sleep 1
echo ""
echo "[#]> Mr.s0s tamvan kan ... " | lolcat
sleep 6
exit
}

echo ""
echo -e $green" 01] Red Hawk" | lolcat
echo -e $green" 02] D-Tect" | lolcat
echo -e $green" 03] Hunner" | lolcat
echo -e $green" 04] WPScan" | lolcat
echo -e $green" 05] Webdav" | lolcat
echo -e $green" 06] Metasploit" | lolcat
echo -e $green" 07] Kali Nethunter" | lolcat
echo -e $green" 08] Ubuntu" | lolcat
echo -e $green" 09] Youtube Dl" | lolcat
echo -e $green" 10] viSQL " | lolcat
echo -e $green" 11] Weeman" | lolcat
echo -e $green" 12] WFDroid" | lolcat
echo -e $green" 13] FBBrute" | lolcat
echo -e $green" 14] Ngrok" | lolcat
echo -e $green" 15] Torshammer " | lolcat
echo -e $green" 16] RouterSploit " | lolcat
echo -e $green" 17] Hydra " | lolcat
echo -e $green" 18] Weevely " | lolcat
echo -e $green" 19] SQLMap " | lolcat
echo -e $green" 20] Dirbuster " | lolcat
echo -e $green" 21] admin finder " | lolcat
echo -e $green" 22] lokomedia exploiter " | lolcat
echo -e $green" 23] elfinder exploiter " | lolcat
echo -e $green" 24] magento add admin exploiter " | lolcat
echo -e $green" 25] scanner tools " | lolcat
echo -e $green" 26] bing dorker " | lolcat
echo -e $green" 27] katoolin " | lolcat
echo -e $green" 28] arch linux " | lolcat
echo -e $green" 29] linux fedora" | lolcat
echo -e $green" 30] hash-buster" | lolcat
echo -e $green" 31] sudo" | lolcat
echo -e $green" 32] aircrack-ng" | lolcat
echo -e $green" 33] joomscan" | lolcat
echo -e $green" 34] bing-ip2hosts" | lolcat
echo -e $green" 35] BlueMaho" | lolcat
echo -e $green" 36] Bluepot" | lolcat
echo -e $green" 37] honeypot" | lolcat
echo -e $green" 38] bot auto deface 1" | lolcat
echo -e $green" 39] bot auto deface 2" | lolcat
echo -e $green" 40] mailer sender cli" | lolcat
echo -e $green" 41] Wordpress Brute Force" | lolcat
echo -e $green" 42] Oh-myzsh theme for termux" | lolcat
echo -e $green" 43] instabot (instagram bot)" | lolcat
echo -e $green" 44] fsociety" | lolcat
echo -e $green" 45] Cms Scanner" | lolcat
echo -e $green" 46] Information Gathering" | lolcat
echo -e $green" 47] com_fabrik exploiter" | lolcat
echo -e $green" 48] com foxcontact exploiter" | lolcat
echo -e $green" 49] gmail brute force" | lolcat
echo -e $green" 50] ezsploit" | lolcat
echo -e $green" 51] spammer-grab sms" | lolcat
echo -e $green" 52] spammer call toko-pedia" | lolcat
echo -e $green" 53] The Fat Rat" | lolcat
echo -e $green" 54] IPGeolocation" | lolcat
echo -e $green" 55] exit" | lolcat
echo -e $white""
read -p "Mr.s0s@Root:~# " act;

if [ $act = 01 ] || [ $act = 01 ]
then
clear
echo " Installing Red Hawk " | lolcat
sleep 1
apt update && apt upgrade
apt install php
apt install git
git clone https://github.com/Tuhinshubhra/RED_HAWK
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 02 ] || [ $act = 02 ]
then
clear
echo " Installing D-Tect " | lolcat
sleep 1
apt-get update && apt-get upgrade
apt-get install git
apt-get install python
git clone https://github.com/shawarkhanethicalhacker/D-TECT
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 03 ] || [ $act = 03 ]
then
clear
echo " Installing Hunner " | lolcat
sleep 1
apt-get update && apt-get upgrade
apt install python
apt install git
git clone https://github.com/b3-v3r/Hunner
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 04 ] || [ $act = 04 ]
then
clear
echo " Installing Wpscan " | lolcat
sleep 1
apt-get update && apt-get upgrade
apt install ruby
apt install curl
apt install git
git clone https://github.com/wpscanteam/wpscan
cd ~/wpscan
gem install bundle
bundle config build.nokogiri --use-system-libraries
bundle install
ruby wpscan.rb --update
cd ~/
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 05 ] || [ $act = 05 ]
then
clear
echo " Installing Webdav " | lolcat
sleep 1
apt update && apt upgrade
apt install python
apt-get install python-pip
pip2 install urllib3 chardet certifi idna requests
apt install openssl curl
pkg install libcurl
mkdir webdav
cd ~/webdav
wget https://pastebin.com/raw/HnVyQPtR -O webdav.py
chmod 777 webdav.py
cd ~/
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 06 ] || [ $act = 06 ]
then
clear
echo " Installing Metasploit " | lolcat
sleep 1
apt update && apt upgrade
apt install git
apt install wget
wget https://raw.githubusercontent.com/verluchie/termux-metasploit/master/install.sh
chmod 777 install.sh
sh install.sh
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 07 ] || [ $act = 07 ]
then
clear
echo -e $green" Installing Kali Nethunter " | lolcat
sleep 1
apt update && apt upgrade
apt install git
git clone https://github.com/Hax4us/Nethunter-In-Termux.git
cd ~/Nethunter-In-Termux
chmod 777 kalinethunter
sh kalinethunter
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 08 ] || [ $act = 08 ]
then
clear
echo -e $green" Installing Ubuntu " | lolcat
sleep 1
apt update && apt upgrade
apt install git
apt install wget
apt install proot
git clone https://github.com/Neo-Oli/termux-ubuntu.git
cd ~/termux-ubuntu
chmod +x ubuntu.sh
sh ubuntu.sh
echo " Fix network please wait "
sleep 1
echo "nameserver 8.8.8.8" > /data/data/com.termux/files/home/termux-ubuntu/ubuntu-fs/etc/resolv.conf
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 09 ] || [ $act = 09 ]
then
clear
echo -e $green" Installing Youtube DL " | lolcat
sleep 1
apt update && apt upgrade
apt install python
pip3 install mps_youtube
pip3 install youtube_dl
apt install mpv
echo " Untuk menjalankannya ketik "mpsyt" tanpa tanda petik "
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 10 ] || [ $act = 10 ]
then
clear
echo -e $green" Installing viSQL " | lolcat
sleep 1
apt update && apt upgrade
pkg install git
pkg install python
git clone https://github.com/blackvkng/viSQL.git
cd ~/viSQL
chmod 777 viSQL.py
cd ~/
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 11 ] || [ $act = 11 ]
then
clear
echo -e $green" Installing Weeman " | lolcat
sleep 1
apt update && apt upgrade
pkg install git
apt install python2
git clone https://github.com/samyoyo/weeman
cd ~/weeman
pip2 install beautifulsoup
pip2 install bs4
cd ~/
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 12 ] || [ $act = 12 ]
then
clear
echo -e $green" Installing WFDroid " | lolcat
sleep 1
apt update && apt upgrade
apt install wget
mkdir wfdroid
cd ~/wfdroid
wget https://raw.githubusercontent.com/bytezcrew/wfdroid-termux/master/wfdinstall
chmod 777 wfdinstall
sh wfdinstall
cd ~/
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 13 ] || [ $act = 13 ]
then
clear
sleep 1
echo -e $green" Installing FBBrute " | lolcat
apt install python2
apt install python2-dev
apt install wget
pip2 install mechanize
mkdir fbbrute
cd ~/fbbrute
wget https://pastebin.com/raw/aqMBt2xA -O fbbrute.py
wget http://override.waper.co/files/password.apk -O wordlist.txt
chmod 777 fbbrute.py
cd ~/
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 14 ] || [ $act = 14 ]
then
clear
echo -e $green" Installing Ngrok " | lolcat
sleep 1
apt install wget
mkdir ngrok
cd ~/ngrok
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip
unzip ngrok-stable-linux-arm.zip
cd ~/
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 15 ] || [ $act = 15 ]
then
clear
echo -e $green "installing torshammer" | lolcat
sleep 1
pkg update
pkg upgrade
pkg install python
pkg install git
git clone https://github.com/cyweb/hammer
cd ~/
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 16 ] || [ $act = 16 ]
then
clear
echo -e $green" Installing Routersploit " | lolcat
sleep 1
apt install git
apt install python2
pip2 install requests
git clone https://github.com/reverse-shell/routersploit.git
cd routersploit
pip install -r requirements.txt
termux-fix-shebang rsf.py
cd ~/
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 17 ] || [ $act = 17 ]
then
clear
echo -e $green" Installing Hydra " | lolcat
sleep 1
apt update && apt install -y wget
apt install hydra
wget http://scrapmaker.com/download/data/wordlists/dictionaries/rockyou.txt
cd ~/
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 18 ] || [ $act = 18 ]
then
clear
echo -e $green" Installing Weevely " | lolcat
sleep 1
pkg update
pkg upgrade
git clone https://github.com/glides/Weevely
cd ~/
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 19 ] || [ $act = 19 ]
then
clear
echo -e $green" Installing SQLMap " | lolcat
sleep 1
apt update && apt upgrade
apt install python2
git clone https://github.com/sqlmapproject/sqlmap.git
cd ~/
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 20 ] || [ $act = 20 ]
then
clear
echo -e $green" Installing Dirbuster " | lolcat
sleep 1
apt-get update
apt-get install python
apt-get install git
git clone https://github.com/maurosoria/dirsearch.git
cd ~/
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 21 ] || [ $act = 21 ]
then
clear
echo -e $green" Installing admin finder " | lolcat
sleep 1
apt update && apt upgrade
apt-get install php
mkdir adfin
cd ~/webdav
wget https://pastebin.com/raw/32txZ6Qr -O adfin.php
cd ~/
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 22 ] || [ $act = 22 ]
then
clear
echo -e $green" installing lokomedia exploiter " | lolcat
sleep 1
apt update && apt upgrade
apt-get install php
mkdir lokomed
cd ~/lokomed
wget https://pastebin.com/raw/sPpJRjCZ -O lokomedia.php
cd ~/
echo -e $red" Udah Ke install coeg " | lolcat
echo -e $red" usage : php lokomedia.php a.txt " | lolcat
fi

if [ $act = 23 ] || [ $act = 23 ]
then
clear
echo -e $green" installing elfinder exploiter " | lolcat
sleep 1
apt update && apt upgrade
apt-get install php
mkdir elfinder
cd ~/elfinder
wget https://pastebin.com/raw/S7Y2V19h -O elfinder.php
cd ~/
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 24 ] || [ $act = 24 ]
then
clear
echo -e $green" installing magento add admin exploiter " | lolcat
sleep 1
apt update && apt upgrade
apt-get install php
mkdir magento
cd ~/magento
wget https://pastebin.com/raw/PXkG73pG -O magento.php
cd ~/
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 25 ] || [ $act = 25 ]
then
clear
echo -e $green" installing scanner tools " | lolcat
sleep 1
apt update && apt upgrade
apt install python
mkdir scanner
cd ~/scanner
wget https://pastebin.com/raw/m79t1Zia -O scanner.py
wget https://pastebin.com/raw/mgKxMWXh -O admins.1337
wget https://pastebin.com/raw/EafKj98D -O files.1337
cd ~/
echo " Udah Ke install coeg " | lolcat
echo " usage : python2 scanner.py site.com -m files " | lolcat
fi

if [ $act = 26 ] || [ $act = 26 ]
then
clear
echo -e $green" installing bing dorker " | lolcat
sleep 1
apt update && apt upgrade
apt-get install php
mkdir bing
cd ~/bing
wget https://pastebin.com/raw/tjQY6Tsg -O dorker.php
cd ~/
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 27 ] || [ $act = 27 ]
then
clear
echo -e $green" installing katoolin " | lolcat
sleep 1
apt update && apt upgrade
pkg install git
pkg install python
pkg install gnupg
pkg install nano
git clone https://github.com/LionSec/katoolin.git
cd ~/katoolin
echo -e $green"note :  nano katoolin.py ganti semua kode /etc/apt/source.list dengan /data/data/com.termux/files/usr/etc/apt/sources.list kemudian simpan dengan menekan ctrl O enter kemudian ctrl X . jika tidak ada menu ctrl pada keyboard munculkan dengan menahan tombol volume atas kemudian ketik Q pada keyboard maka menu ctrl akan muncul di atas keyboard
python2 katoolin.py
Sisanya bisa mengikuti cara install di atas, Jika menemui masalah gpg error saat melakukan add repository install gnupg-curl dengan perintah pkg install gnupg-curl
Untuk yg menggunakan termux dengan cpu arm64 (aarch64) tidak bisa menambahkan repositori kali linux karna kali linux tidak support aarch64, jadi sebelum menginstall tools kali di termux wajib dengan android dengan arm32 jika arm64 gunakan gnuroot"
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 28 ] || [ $act = 28 ]
then
clear
echo -e $green" installing arch linux " | lolcat
sleep 1
apt update && apt upgrade
apt-get install git
cd ~/
git clone https://github.com/sdrausty/termux-archlinux.git
cd termux-archlinux 
chmod +x setupTermuxArch.sh
./setupTermuxArch.sh
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 29 ] || [ $act = 29 ]
then
clear
echo -e $green" installing fedora " | lolcat
sleep 1
apt update && apt upgrade
apt-get install git
apt install wget
git clone https://github.com/nmilosev/termux-fedora.git
cd termux-fedora
chmod +x termux-fedora.sh
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 30 ] || [ $act = 30 ]
then
clear
echo -e $green" installing hash-Buster " | lolcat
sleep 1
apt update && apt upgrade
apt install python2 && apt install git
git clone https://github.com/UltimateHackers/Hash-Buster
cd Hash-Buster
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 31 ] || [ $act = 31 ]
then
clear
echo -e $green" installing sudo " | lolcat
sleep 1
apt update && apt upgrade
pkg install git ncurses-utils
git clone https://github.com/st42/termux-sudo.git
cd termux-sudo
cat sudo > /data/data/com.termux/files/usr/bin/sudo
chmod 700 /data/data/com.termux/files/usr/bin/sudo
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 32 ] || [ $act = 32 ]
then
clear
echo -e $green" installing aircrack-ng " | lolcat
sleep 1
apt-get update && apt-get upgrade
apt-get install aircrack-ng
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 33 ] || [ $act = 33 ]
then
clear
echo -e $green" installing joomscan " | lolcat
sleep 1
apt-get update && apt-get upgrade
apt-get install git
apt-get install perl
git clone https://github.com/rezasp/joomscan.git
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 34 ] || [ $act = 34 ]
then
clear
echo -e $green" installing bing-ip2hosts " | lolcat
sleep 1
apt-get update && apt-get upgrade
apt-get install wget
wget http://www.morningstarsecurity.com/downloads/bing-ip2hosts-0.4.tar.gz && tar -xzvf bing-ip2hosts-0.4.tar.gz && cp bing-ip2hosts-0.4/bing-ip2hosts /usr/local/bin/t
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 35 ] || [ $act = 35 ]
then
clear
echo -e $green" installing BlueMaho " | lolcat
sleep 1
apt-get update && apt-get upgrade
apt-get install git
git clone git://git.kali.org/packages/bluemaho.git
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 36 ] || [ $act = 36 ]
then
clear
echo -e $green" installing Bluepot " | lolcat
sleep 1
apt-get update && apt-get upgrade
apt-get install git
git clone git://git.kali.org/packages/bluepot.git
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 37 ] || [ $act = 37 ]
then
clear
echo -e $green" installing honeypot " | lolcat
sleep 1
apt-get update && apt-get upgrade
apt-get install git && apt-get install php
git clone https://github.com/whackashoe/php-spam-mail-honeypot.git
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 38 ] || [ $act = 38 ]
then
clear
echo -e $green" installing bot auto deface 1 " | lolcat
sleep 1
apt-get update && apt-get upgrade
apt-get install git 
apt-get install wget 
apt-get install perl 
apt-get install unzip
git clone https://github.com/mrcakil/bot.git
cd bot
unzip bot.zip
chmod 777 bot.pl
echo -e $red" Lokasi bot ? /bot/bot.pl"
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 39 ] || [ $act = 39 ]
then
clear
echo -e $green" installing bot auto deface 2 " | lolcat
sleep 1
apt-get update && apt-get upgrade
apt-get install git && apt-get install perl
git clone https://github.com/Moham3dRiahi/XAttacker
cd XAttacker
chmod 777 XAttacker.pl
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 40 ] || [ $act = 40 ]
then
clear
echo -e $green" installing mailer-sender " | lolcat
sleep 1
apt-get update && apt-get upgrade
apt-get install php5-cli
curl -sS https://getcomposer.org/installer | php
chmod +x composer.phar
sudo mv composer.phar /usr/bin/composer
git clone https://github.com/pedro-stanaka/mailer-cli.git
echo -e $red" note !! "
echo -e $red" usage php sendmail.php notification:mailer <email> <subject> <body>; "
echo -e $red" or "
echo -e $red" php sendmail.php --help "
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 41 ] || [ $act = 41 ]
then
clear
echo -e $green" installing wordpress brute force " | lolcat
sleep 1
apt-get update && apt-get upgrade
apt-get install python
apt-get install python-pip
pip install request
git clone https://github.com/atarantini/wpbf
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 42 ] || [ $act = 42 ]
then
clear
echo -e $green" installing termux Ohmyzsh " | lolcat
sleep 1
apt-get update && apt-get upgrade
sh -c "$(curl -fsSL https://github.com/Cabbagec/termux-ohmyzsh/raw/master/install.sh)"
~/.termux/colors.sh
echo -e $red" ganti color ? ketik ~/.termux/colors.sh "
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 43 ] || [ $act = 43 ]
then
clear
echo -e $green" installing Instabot instagram bot " | lolcat
sleep 1
apt-get update && apt-get upgrade
pkg install python
apt-get install git
apt-get install nano
git clone https://github.com/instabot-py/instabot.py
echo " Udah Ke install coeg " | lolcat
echo -e $red" Please wait... "
echo -e $red" Please wait... "
sleep 1
cd instabot.py
echo -e $red" ketik nano example.py "
echo -e $red" masukan username dan password mu"
echo -e $red" Ok " | lolcat
fi


if [ $act = 44 ] || [ $act = 44 ]
then
clear
echo -e $green" installing fsociety " | lolcat
sleep 1
apt-get update && apt-get upgrade
pkg install python
apt-get install git
git clone https://github.com/Manisso/fsociety
echo " Udah Ke install coeg " | lolcat
echo -e $red" Please wait... "
echo -e $red" Please wait... "
sleep 1
cd fsociety
echo -e $red" python fsociety.py "
fi


if [ $act = 45 ] || [ $act = 45 ]
then
clear
echo -e $green" installing  CMS Scanner " | lolcat
sleep 1
apt-get update && apt-get upgrade
pkg install python
apt-get install git
git clone https://github.com/Dionach/CMSmap.git
sleep 1
cd CMSmap
echo -e $red" Usage: cmsmap.py -t <URL> "
fi

if [ $act = 46 ] || [ $act = 46 ]
then
clear
echo -e $green" installing INFORMATION Gathering " | lolcat
sleep 1
apt-get update && apt-get upgrade
pkg install python
apt-get install git
git clone https://github.com/m4ll0k/Infoga.git infoga
sleep 1
cd infoga
pip install -r req
echo -e $red" Usage: python infoga.py "
fi


if [ $act = 47 ] || [ $act = 47 ]
then
clear
echo -e $green" installing com fabrik exploiter " | lolcat
sleep 1
apt-get update && apt-get upgrade
apt-get install wget
apt-get install php
wget https://pastebin.com/raw/LDvFvtUD -O com_fabrik.php
sleep 1
echo -e $red" Usage: php com_fabrik.php target.txt "
fi


if [ $act = 48 ] || [ $act = 48 ]
then
clear
echo -e $green" installing com foxcontact exploiter  " | lolcat
sleep 1
apt-get update && apt-get upgrade
apt-get install wget
apt-get install php
wget https://pastebin.com/raw/EAtSir5V -O com_foxcontact.php
sleep 1
echo -e $red" Usage: php com_foxcontact.php target.txt "
fi

if [ $act = 49 ] || [ $act = 49 ]
then
clear
echo -e $green" installing gmail brute force " | lolcat
sleep 1
apt-get update && apt-get upgrade
apt-get install git
git clone https://github.com/JamesAndresCM/Brute_force_gmail
sleep 1
echo -e $red" Usage: python2.7 brute_force_gmail.py example@gmail.com PATH_TO_DICTIONARY "
fi


if [ $act = 50 ] || [ $act = 50 ]
then
clear
echo -e $green" installing ezsploit " | lolcat
sleep 1
apt-get update && apt-get upgrade
apt-get install git
git clone https://github.com/rand0m1ze/ezsploit
sleep 1
echo -e " Udah Ke install coeg " | lolcat
fi

if [ $act = 51 ] || [ $act = 51 ]
then
clear
echo -e $green" installing spammer grab " | lolcat
sleep 1
apt-get update && apt-get upgrade
apt-get install git
apt-get install python
pip install requests
git clone https://github.com/p4kl0nc4t/Spammer-Grab/
sleep 1
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 52 ] || [ $act = 52 ]
then
clear
echo -e $green" installing spammer toko pedia " | lolcat
sleep 1
apt-get update && apt-get upgrade
apt-get install git
apt-get install unzip
git clone https://github.com/mrcakil/spam
cd spam
unzip toko-pedia.zip
sleep 1
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 53 ] || [ $act = 53 ]
then
clear
echo -e $green" installing TheFatRat " | lolcat
sleep 1
apt-get update && apt-get upgrade
apt-get install git
git clone https://github.com/Screetsec/TheFatRat.git
cd TheFatRat
chmod +x setup.sh && ./setup.sh
sleep 1
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 54 ] || [ $act = 54 ]
then
clear
echo -e $green" installing IPGeolocation " | lolcat
sleep 1
apt-get update && apt-get upgrade
apt-get install git
apt install python
git clone https://github.com/maldevel/IPGeolocation.git
cd IPGeolocation
chmod +x ipgeolocation.py
pip install -r requirements.txt
sleep 1
echo " Udah Ke install coeg " | lolcat
fi

if [ $act = 55 ] || [ $act = 55 ]
then
echo " Gunakan Kontools ini dengan bidjak ea coeg" | lolcat
sleep 1
echo " Gua mau curhat nihh tod" | lolcat
sleep 1
echo " Gua lagi sange " | lolcat
sleep 1
echo " loading dulu... " | lolcat
echo " contact me : 08878819132 " | lolcat
echo " jangan kangen yahh " | lolcat
sleep 1
exit
fi
